# Homework 1
## 1.1. 간단한 Spark 예제

Click on the “Run” button for the next two cells or type `[Shift]-[Enter]`.  
조금 기다리면 5 element가 들어있는 array가 생깁니다. 

아래 코드는 당장 이해할 필요는 없습니다, 아직 설명드린 부분은 아니지만, Spark가 잘 설치되었는지 확인할 수 있는 코드입니다.

In [16]:
import pyspark
sc = pyspark.SparkContext('local[*]')
rdd = sc.parallelize(range(1000))
take5 = rdd.takeSample(False, 5, seed=314)

ValueError: Cannot run multiple SparkContexts at once; existing SparkContext(app=pyspark-shell, master=local[*]) created by __init__ at <ipython-input-15-37b8b762dcb2>:2 

In [17]:
display(take5)

[623, 361, 418, 299, 519]

## 1.2 Something a Little More Fun

아래 cell에 들어있는 코드를 다음 요구사항에 맞게 변형하여 그림을 출력하게 해보세요:

1. The text (which says “student”) should be your student number
2. Sample된 수가 150이 되게 변경하고, 이에 맞추어서 figure의 title을 바꿔주세요
3. x-축이 “Sample number” 가 되도록 변경해주세요.

각 cell은 반복적으로 실행시킬 수 있습니다. 채점을 할때에는, 조교님이 전체 cell을 run하여 확인을 하게 됩니다. 
제출전에 Kernel menu에서 "Restart & Run All"를 실행하여 버그가 있는지 확인해보시기를 추천 드립니다. 

In [1]:

import matplotlib.pyplot as plt
import numpy as np

# Sample 100 values from the RDD
y = np.array(rdd.takeSample(False, 150, 1))
# Create an array with the indices
x = np.array(range(len(y)))

# Create a plot with a caption, X and Y legends, etc
x_label = 'Sample number'
y_label = 'Value'
student = '20175130'

plt.title(str(len(y)) + ' random samples from the RDD')
plt.xlabel(x_label)
plt.ylabel(y_label)
plt.figtext(0.995, 0.01, student, ha='right', va='bottom')
# Scatter plot that fits within the box
plt.scatter(x, y)
plt.tight_layout()

# Now fit a trend line to the data and plot it over the scatter plot
m, c = np.polyfit(x, y, 1)
plt.plot(x, m*x + c)

# Save the SVG
plt.savefig('hw1.svg')

NameError: name 'rdd' is not defined

In [21]:
# 확인용 cell 입니다. 변경하지 마세요
print("Your student number is:", student)

Your student number is: 20175130


In [0]:
# 확인용 cell 입니다. 변경하지 마세요
print("You have sampled", len(y), "points.")

You have sampled 100 points.


In [0]:
# 확인용 cell 입니다. 변경하지 마세요
print("The label on the x-axis says:", x_label)

The label on the x-axis says: Sample no


# Python  기초

이진우 작성. <빠르게 활용하는 파이썬 3.6 프로그래밍(신호철 외 작성, 위키북스)> 참조

## 1. 자료형 및 연산자

### (1) 변수명

 <규칙>
 
     (1) 영문자(대, 소문자 구분), 숫자, 언더바(\_) 사용 가능
 
     (2) 첫 자리에는 숫자 사용 불가능
 
     (3) 예약어 사용 불가능
 
 <예약어 목록>

and as assert break class continue def del elif else except is 

finally for from global if import in is lambda nonlocal not or 

pass raise retrun try while with yield 등등...!
 

In [0]:
friend = 1 
Friend = 10 

python_jjang = 'python?'
Python_jjang = 'python!'

print(friend)
print(Friend)
print(python_jjang)
print(Python_jjang)

1
10
python?
python!


In [0]:
# 첫 자리에 숫자를 사용한 경우 SyntaxError 발생
1hihi = "???"

SyntaxError: invalid syntax (<ipython-input-17-768c54fbe978>, line 2)

In [0]:
# 예약어를 사용한 경우 SyntaxError 발생
for = 1

SyntaxError: invalid syntax (<ipython-input-18-d820c56aa5aa>, line 2)

### (2)수치

Python에서 표현할 수 있는 수치형은

`int` `long` `float` `complex`

3.x 버젼부터 long형은 int로 통합 됨

### int와 long

정수를 값으로 입력하면 10진수 정수로 인식

In [0]:
year = 2019
month = 8
print(year, month)

2019 8


정수 앞에 'Oo' ==> 8진수로 인식

정수 앞에 'Ob' ==> 2진수로 인식

정수 앞에 'Ox' ==> 16진수로 인식

<출력방법>

In [0]:
print("{:o}".format(10)) # 8진수 출력
print("{:b}".format(10)) # 2진수 출력
print("{:x}".format(11)) # 16진수 출력
print("{:d}".format(10))

12
1010
b
10


### float과 complex

실수 & 복수

In [0]:
print(type(3.14))
print(type(314e-2))
print(type(3-4j))

<class 'float'>
<class 'float'>
<class 'complex'>


### (3) 문자열

`'` 또는 `"`로 지정. 시작한 기호로 반드시 끝나야 함!

In [0]:
x = 'python1'
y = "python2"
z = "python3' # error 발생

SyntaxError: EOL while scanning string literal (<ipython-input-23-a71ca5a9b568>, line 3)

### 다량의 문자열 넣기와 이스케이프 문자를 이용한 출력 설정

(1) `"""` 또는 `'''`로 시작

(2) 이스케이프 문자 사용

     \n : 개행
 
     \t : 탭
 
     \\ : \를 문자로 사용
 
     \' or \" : ' 또는 "를 문자로 사용

In [0]:
print(""" 집에 가고 싶다. 집에 가고 싶다
벌써 새벽 3시. 배고프다. 먹으면 살찐다. 종강은 언제올까. 앞이 보이질 않는다..
""")

 집에 가고 싶다. 집에 가고 싶다
벌써 새벽 3시. 배고프다. 먹으면 살찐다. 종강은 언제올까. 앞이 보이질 않는다..



In [0]:
print("\t집\n에는 카레가 있는데..\n")
print("\'집\'에는 \\카레\\가 있을까.. \"")

	집
에는 카레가 있는데..

'집'에는 \카레\가 있을까.. "


### 문자열 연산자와 인덱싱[슬라이싱]

<문자열 연산자>

In [0]:
print("Python" + "과 R") # + 사용
print("Python" "과 R\n") 
print("둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.\n" * 10) # * 사용

Python과 R
Python과 R

둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.
둘 중 무엇을 해야할까, 둘 다 해야할 것 같다.



<문자열 인덱싱 & 슬라이싱> 

![대체 텍스트](https://python.bakyeono.net/img/img-5-2.png)



In [0]:
a = "Hello World"

print("!!!!문자열 인덱싱!!!")
print(a[0]) # 첫 번째 위치 문자 출력
print(a[-11]) # 첫 번째 위치 문자 출력
print(a[4]) # 다섯 번째 위치 문자 출력
print(a[-4]) # 다섯 번째 위치 문자 출력
print(a[-1]) # 마지막 위치 문자 출력
print(a[10]) # 마지막 위치 문자 출력

print("!!!!문자열 슬라이싱!!!")
print(a[0:5]) # 처음부터 다섯 번째 까지
print(a[0:]) # 처음부터 끝까지
print(a[:]) # 처음부터 끝까지
print(a[-2:]) # 뒤에서 두 번째부터 끝까지
print(a[-3:]) # 뒤에서 세 번째부터 끝까지

!!!!문자열 인덱싱!!!
H
H
o
o
d
d
!!!!문자열 슬라이싱!!!
Hello
Hello World
Hello World
ld
rld


### (4) 리스트

    여러 종류의 값을 담을 수 있는 자료형. 즉, 값의 나열!

    0부터 인덱스 및 슬라이싱 가능
    
    append, insert, extend, pop, remove, index 등 지원   

In [0]:
colors = ['red', 'blue', "핫핑크"]
print(colors)
type(colors)

['red', 'blue', '핫핑크']


list

In [0]:
# append를 이용한 값의 추가(맨 뒤)
colors.append('나는 금색이 좋아')
print(colors)

['red', 'blue', '핫핑크', '나는 금색이 좋아']


In [0]:
# insert를 이용한 특정 위치에 값 추가
colors.insert(1, "나는 은색이 좋다네")
print(colors)

['red', '나는 은색이 좋다네', 'blue', '핫핑크', '나는 금색이 좋아']


In [0]:
# externd를 이용한 다중 값 추가
colors.extend(["허연색", "까무잡잡한색"])
print(colors)

['red', '나는 은색이 좋다네', 'blue', '핫핑크', '나는 금색이 좋아', '허연색', '까무잡잡한색']


In [0]:
# index를 이용한 특정 값의 인덱스 반환
print(colors.index("허연색"))
print(colors.index("까무잡잡한색"))

5
6


In [0]:
# count, pop, remove
print(colors.count("핫핑크")) # count를 이용한 특정 값의 개수 파악
print(colors.pop(3)) # pop을 이용한 특정 위치의 값 추출
colors.remove("나는 금색이 좋아") # remove를 이용한 특정 값 삭제
print(colors)

1
핫핑크
['red', '나는 은색이 좋다네', 'blue', '허연색', '까무잡잡한색']


### (5) 세트

    list와 유사하게 값의 나열. 하지만, 순서는 없다!

In [0]:
a = {1, 2, 3}
b = {3, 4, 5}
print(type(a))
print(type(b))

<class 'set'>
<class 'set'>


In [0]:
union_a_b = a.union(b) # 합집합
union_a_b_2 = a | b # 합집합
inter_a_b = a.intersection(b) # 교집합
inter_a_b_2 = a & b # 교집합

print(union_a_b)
print(union_a_b_2)
print(inter_a_b)
print(inter_a_b_2)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}
{3}
{3}


### (6) 튜플

    list와 유사하게 값의 나열. 하지만, []가 아닌 ()로 표현되며, 수정 붉가능(읽기전용)
       
    제공되는 method는 count(), index() 뿐
    
    참고로 여러 값을 다중 할당하는 경우 튜플이 사용 됨.!

In [0]:
t = (1,2,3)
print(type(t))

<class 'tuple'>


In [0]:
a, b = 1, 2
print(a, b)
(a, b) = (1, 2)
print(a, b)

1 2
1 2


### (7) 사전

    키(key)와 값(value)의 쌍으로 구성된 자료형. 단, 인덱스는 지원하지 않는다.

In [0]:
d = dict(a = 1, b = 3, c = 5)
print(d)
print(type(d))

{'a': 1, 'b': 3, 'c': 5}
<class 'dict'>


In [0]:
color = {"apple" : "사과는 빨간색인가", "banana" : "바나나는 금색인가요?"}
print(color)


{'apple': '사과는 빨간색인가', 'banana': '바나나는 금색인가요?'}


In [0]:
# index의 미지원
color[0]

KeyError: 0

In [0]:
color["apple"]

'사과는 빨간색인가'

#### 새로운 값의 할당과 값의 변경

In [0]:
# 변수["새로운 키"] = 값
color["melon"] = "이거 스펠링 맞나.."
color

{'apple': '사과는 빨간색인가', 'banana': '바나나는 금색인가요?', 'melon': '이거 스펠링 맞나..'}

In [0]:
color["melon"] = "맞는 것 같기도 하고.."
color

{'apple': '사과는 빨간색인가', 'banana': '바나나는 금색인가요?', 'melon': '맞는 것 같기도 하고..'}

#### items()  keys() values()
    itemss() : 사전 값 반환
    
    keys() : 키 반환
    
    values() : 값 반환

In [0]:
for temp in color.items():
    print(temp)

('apple', '사과는 빨간색인가')
('banana', '바나나는 금색인가요?')
('melon', '맞는 것 같기도 하고..')


In [0]:
for temp in color.keys():
    print(temp)

apple
banana
melon


In [0]:
for temp in color.values():
    print(temp)

사과는 빨간색인가
바나나는 금색인가요?
맞는 것 같기도 하고..


## 2. 함수

함수 선언 문법
   
def <함수명>(인자1, 인자2, ...N):

    <구문>
    
    return <반환값>

In [0]:
def Times(a, b):
    return a + b

print(Times)
print(Times(10,10))

<function Times at 0x000001E058EF3488>
20


#### return

함수를 종료하고 해당 함수를 호출한 곳으로 되돌아 감.

어떤 종류의 객체도 반환 가능 & 여러 값을 튜플로 묶어서 처리할 수 있음

In [0]:
# 반환 값(return)이 없는 경우
def setValue(newValue):
    x = newValue
    
retval = setValue(10)
print(retval)

None


In [0]:
def setValue(newValue):
    x = newValue
    return x
retval = setValue(10)
print(retval)

10


In [0]:
# 튜플을 이용한 여러 값 return

def swap(x, y):
    return y, x

print(swap(1,2))

a, b = swap(1, 2) # 튜플을 이용한 여러 값 반환
print(a, " ", b)

(2, 1)
2   1


In [0]:
# 입력받은 두 개의 리스트에서 교집합을 구한 후 리스트로 return
def intersect(prelist, postlist):
    result_list = []
    for x in prelist:
        if x in postlist and x not in result_list:
            result_list.append(x)
    return result_list

list1 = ["빨간맛", "이상한맛", "토나오는맛"]
list2 = ["파랑맛", "토나오는맛","노랑맛"]
intersect(list1,list2)

['토나오는맛']

### (1) 스코핑 룰

함수는 별도의 namespace를 가짐. 


<LGB 규칙> ---> `L > G > B`

함수 내부의 `지역 영역(Local scopre)`

함수 외부의 `전역 영역(Global scopre)`

파이썬 자체의 정의내용에 대한 `내장 영역(Built-in scope)`.

In [0]:
# 함수 내 지역 영역에 해당 이름이 없기 때문에 전역 영역에서 찾아옴
x = 1
def func(a):
    return a + x
print(func(1))

2


In [0]:
# 함수 내 지역 영역에 x라는 이름이 있는 경우, 지역 영역의 변수 사용
def func2(a):
    x = 100
    return a + x
print(func2(2))
print(x)

102
1


In [0]:
# 만약 지역 영역에서 전역 영역의 변수를 사용할 경우 
g = 1
def testScope(a):
    global g
    g = 2
    return g + a

print(testScope(1))
print(g)

3
2


### (2) 함수 인자

#### 기본 인자 값

In [0]:
# 기본 값 설정
def Times(a = 10, b = 20):
    return a * b
print(Times())
print(Times(a = 1, b = 2))
print(Times(5)) # a에만 할당

200
2
100


#### 가변 인자 리스트

가변 인자 리스트는 튜플로 처리 됨

In [0]:
def test(*args):
    print(type(args))
test(1,2,3,4,5)

<class 'tuple'>


In [0]:
def union2(*hehe):
    res = []
    for item in hehe:
        for x in item:
            if not x in res:
                res.append(x)
    return res

union2("HAM", "EGG", "SPAM")

['H', 'A', 'M', 'E', 'G', 'S', 'P']

### (3) 람다 함수

이름 없는 함수... 메모리 공간에 적재되지 않고 사용 후 즉시 삭제 됨

기본 형태 : lambda 인자 : <구문>

인자1, 인자2, 인자x,... : 출력식1 조건문 else 출력식2

**if 조건식을 사용할 경우 반드시 else 문 작성해야 함**

In [0]:
g = lambda x, y : x * y
print(g(2, 3))
print((lambda x : x* x)(3))

6
9


#### map

인수로 입력 받은 리스트의 원소를 하나씩 입력받은 함수에 적용시키고 결과를 새로운 리스트로 넘김

In [0]:
def sqrt(x):
    x = x*x    
    return x

print(list(map(sqrt, [1,2,3,4,5])))
print(list(map(lambda x: x ** 2, [1,2,3,4,5])))

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


In [0]:
testArr1 = [1,2,3,4,5,6,7,8,9,10]
testArr2 = [2,4,6,7,10,12,14,16,20]

outArr1 = list(map(lambda x : "OK" if x % 2 == 0 else x, testArr1))

outArr2 = list(map(lambda x : "First" if x == 1 else "Second" if x == 2 else x * x, testArr1))

outArr3 = list(map(lambda x, y : x + y, testArr1, testArr2))

print("example 1 : ", outArr1)
print("example 2 : ", outArr2)
print("example 3 : ", outArr3)

example 1 :  [1, 'OK', 3, 'OK', 5, 'OK', 7, 'OK', 9, 'OK']
example 2 :  ['First', 'Second', 9, 16, 25, 36, 49, 64, 81, 100]
example 3 :  [3, 6, 9, 11, 15, 18, 21, 24, 29]


## 3. 클래스

### 클래스 선언


In [0]:
class Person: # 클래스 정의
    name = "Default Name"  # 멤버 변수
    def Person_print(self):      # 멤버 메서드
        print("My Name is {0}".format(self.name))

p1 = Person() # 인스턴스 생성
p1.Person_print() # 멤버 변수값 출력

My Name is Default Name


### 생성자 소멸자

In [0]:
class MyClass:        
    def __init__(self, value): # 생성자 메서드
        self.value = value
        print("Class is created! Value  = ", value)
    
    def __del__(self): # 소멸자 메서드
        print("Class is deleted")

        
def foo():
    d = MyClass(10)
    
foo()

Class is created! Value  =  10
Class is deleted


## 4. Numpy

### Numpy 배열의 기초

무작위 수를 이용한 1차원, 2차원, 3차원 배열 생성

In [0]:
import numpy as np

np.random.seed(0)

x1 = np.random.randint(10, size = 6) # 1차원 배열
x2 = np.random.randint(10, size = (3, 4)) # 2차원 배열
x3 = np.random.randint(10, size = (3, 4, 5)) # 3차원 배열

print(x1, "# 1차원 배열 \n")
print(x2, "# 2차원 배열 \n")
print(x3, "# 3차원 배열 \n")

[5 0 3 3 7 9] # 1차원 배열 

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] # 2차원 배열 

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]] # 3차원 배열 



### 배열 슬라이싱

파이썬 리스트의 구문을 따른다.

```
x[start:stop:step]
```


In [0]:
x = np.arange(10) # 배열 생성(0부터 9까지)
print(x, "\n")

print(x[:5], " ----> x[:5]  첫 다섯 개 요소\n")

print(x[5:], " ----> x[5:]  인덱스 5 다음 요소\n")

print(x[::2], " ----> x[::2]  하나 걸러 하나씩의 요소\n")

print(x[1::2], " ----> x[1::2]  인덱스 1에서 시작해 하나 걸러 하나씩\n")


[0 1 2 3 4 5 6 7 8 9] 

[0 1 2 3 4]  ----> x[:5]  첫 다섯 개 요소

[5 6 7 8 9]  ----> x[5:]  인덱스 5 다음 요소

[0 2 4 6 8]  ----> x[::2]  하나 걸러 하나씩의 요소

[1 3 5 7 9]  ----> x[1::2]  인덱스 1에서 시작해 하나 걸러 하나씩



### 배열 재구조화

**reshape**를 활용. (newaxis를 통한 방법도 있지만.. 필요하다면 찾아볼 것)

In [0]:
grid = np.arange(1, 10)

print(grid, "1차원 배열(9,)을 \n")

grid2 = grid.reshape((3, 3))

print(grid2, "2차원 배열(3, 3)로 재구조화")

[1 2 3 4 5 6 7 8 9] 1차원 배열(9,)을 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 2차원 배열(3, 3)로 재구조화


### 배열 연결 및 분할

#### concatenate

In [0]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

print(np.concatenate([x, y]), "\n") 

# 2개 이상의 배열 연결 가능
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1] 

[ 1  2  3  3  2  1 99 99 99]


In [0]:
# 2차원 배열

grid = np.array([[1, 2, 3], 
                [4, 5, 6]])

# 첫 번째 축을 따라 연결(행)
print(np.concatenate([grid, grid], axis=0), "\n")

# 두 번째 축을 따라 연결(열)
print(np.concatenate([grid, grid], axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


### 배열 연산:브로드캐스팅


In [0]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

a + b

array([5, 6, 7])

**브로드캐스팅을 사용하면 서로 다른 크기의 배열에서 계산을 수행할 수 있다.**

In [0]:
a + 5

array([5, 6, 7])

![대체 텍스트](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)


**브로드캐스팅 규칙**



1.   두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽(왼쪽)을 1로 채운다
2.   두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.
3.   임의의 차원에서 크기가 일치하지도 않고 1도 아니라면 오류 발생

**자세한 예제는 [여기](https://sacko.tistory.com/16?category=630829)를 참고할 것 **

# 간단한 Python 기초 과제


## 모든 과제는 반드시 **주석을 작성할 것** 

## 없을 시 0점 처리

## 과제 1

We add a **Leap Day(윤년)** on February 29, almost *every four years*. The leap day is an extra, or intercalary day and we add it to the shortest month of the year, February.
In the Gregorian calendar three criteria must be taken into account to identify leap years:



*   The year can be evenly divided by 4, is a leap year, unless:
  *   The year can be evenly divided by 100, it is NOT a leap year, unless:
      *   The year is also evenly divisible by 400. Then it is a leap year.

This means that in the Gregorian calendar, the years **2000 and 2400 are leap years**, while **1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years**

### **윤년 계산하는 프로그램입니다.**

---

**입력 값**


```
year = [2000, 2100, 2400, 3455, 1990, 1992, 1800, 1900, 2200, 2300, 2500]
```

---

**출력 예시**

```
[2000, 2100, 2400, 3455, 1990, 1992, 1800, 1900, 2200, 2300, 2500]

True
False
True
False
False
True
False
False
False
False
False
```

In [18]:
year = [2000, 2100, 2400, 3455, 1990, 1992, 1800, 1900, 2200, 2300, 2500]

def is_leap(year):
    if year % 4 == 0: #4로 나누어지면 윤년
        if year % 100 == 0: #4로 나누어 떨어지더라도 100으로 나누어 떨어지면 평년
            if year % 400 == 0: #100으로 나누어 떨어지더라도 400으로 나누어 떨어지면 윤년
                return True     #400으로 나누어 떨어지면 윤년
            return False  #100으로 나누어 떨어지면 평년
        return True  #4로 나누어 떨어지면 윤년
    else:
        return False #4로 나누어 떨어지지 않으면  평년    

print(year) #해를 출력하는 출력문
for y in year:
    print(is_leap(y)) #함수 출력으로 year리스트 안에 있는 인자들을 전부 확인하고 True값과 False값을 나타냄

[2000, 2100, 2400, 3455, 1990, 1992, 1800, 1900, 2200, 2300, 2500]
True
False
True
False
False
True
False
False
False
False
False


## 과제 2

Given **twenty** **positive integers(value)**, ***find the minimum and maximum values*** that can be calculated by summing exactly **nineteen of the** **twenty integers**. Then print the respective minimum and maximum values as a single line of two space-separated long integers.

#### 20 개 중 19개의 정수 선택하여 진행할 것.

---


For example, `arr = [46,960,19,182,365,929,568,627,510,355,313,82,742,656,385,181,827,197,809,413]`. \
Our **minimum sum** is 19+46+82+181+182+197+313+355+365+385+413+510+568+627+656+742+809+827+929 = **8206**.  
Our **maximum sum** is 46+82+181+182+197+313+355+365+385+413+510+568+627+656+742+809+827+929+960 = **9147**.



---

**입력 값**



``` 
value = [46,960,19,182,365,929,568,627,510,355,313,82,742,656,385,181,827,197,809,413]
```



---
**출력 예시**

```
minimum sum = 8206, maximum sum = 9147 
```


In [16]:
value = [46,960,19,182,365,929,568,627,510,355,313,82,742,656,385,181,827,197,809,413]

def miniMaxSum(arr):
    min=arr[0] #최솟값 선정 배열
    max=arr[0] #최댓값 선정 배열
    minsum=0 #최소 합을 더해줄 변수
    maxsum=0 #최대 합을 더해줄 변수
    for num in arr: #배열을 반복문을 통해 돌림
        if min >num: #최솟값을 비교해주는 조건문
            min=num
        if max <num:#최댓값을 비교해주는 조건문
            max=num
    minsum=sum(arr)-max #총 배열합에서 최댓값을 뺴서 최솟값의 합을 구함
    maxsum=sum(arr)-min #총 배열합에서 최솟값을 뺴서 최댓값의 합을 구함
    print("minimum sum=",minsum,"maximum sum=",maxsum) #출력문으로 결과값과 같게 출력함
            
        
  
     # Write your logic here
    
miniMaxSum(value) #함수 출력

minimum sum= 8206 maximum sum= 9147


## 과제 3

Fibonacci 수 구하기

입력된 N 리스트 값에 해당하는 위치의 Fibonacci의 수를 찾자.


---

**입력**

```
N = [2, 15, 20, 30, 35, 40, 150, 200, 1000]
```



---

**출력 예시**


```
input Fibonacci Number
fibo(2) = 1
fibo(15) = 610
fibo(20) = 6765
fibo(30) = 832040
fibo(35) = 9227465
fibo(40) = 102334155
fibo(150) = 9969216677189303386214405760200
fibo(200) = 280571172992510140037611932413038677189525
fibo(1000) = 43466557686937456435688527675040625802564660517371780402481729089536555417949051890403879840079255169295922593080322634775209689623239873322471161642996440906533187938298969649928516003704476137795166849228875


```




In [4]:

def fibo(n): #피보나치를 계산하는 함수 선언 
    a, b = 1, 0 #피보나치 계산을 위한 변수 a,b 선언
    for i in range(n): #반복문 
        a, b = b, a + b 
    return b #결과값 반환

print("input Fibonacci Number") #input Fibonacci Number라는 문구를 뽑아냄
N = [2, 15, 20, 30, 35, 40, 150, 200, 1000] #피보나치로 계산할 리스트를 만듬

for index in N: #반복문을 통해서 N에 있는 리스트를 계산해줌
    print("fibo(%d) = %d" % (index, fibo(index))) 



input Fibonacci Number
fibo(2) = 1
fibo(15) = 610
fibo(20) = 6765
fibo(30) = 832040
fibo(35) = 9227465
fibo(40) = 102334155
fibo(150) = 9969216677189303386214405760200
fibo(200) = 280571172992510140037611932413038677189525
fibo(1000) = 43466557686937456435688527675040625802564660517371780402481729089536555417949051890403879840079255169295922593080322634775209689623239873322471161642996440906533187938298969649928516003704476137795166849228875


## 과제 4(참조 : https://www.acmicpc.net/problem/2941)

예전에는 운영체제에서 크로아티아 알파벳을 입력할 수가 없었다. 따라서, 다음과 같이 크로아티아 알파벳을 변경해서 입력했다.


![대체 텍스트](https://t1.daumcdn.net/cfile/tistory/999D8B365B3D04151E)

예를 들어, ljes=njak은 크로아티아 알파벳 6개(lj, e, š, nj, a, k)로 이루어져 있다. 단어가 주어졌을 때, 몇 개의 크로아티아 알파벳으로 이루어져 있는지 출력한다.

dž는 무조건 하나의 알파벳으로 쓰이고, d와 ž가 분리된 것으로 보지 않는다. lj와 nj도 마찬가지이다. 위 목록에 없는 알파벳은 한 글자씩 센다.



---

**입력**

첫째 줄에 최대 100글자의 단어가 주어진다. 알파벳 소문자와 '-', '='로만 이루어져 있다.

단어는 크로아티아 알파벳으로 이루어져 있다. 문제 설명의 표에 나와있는 알파벳은 변경된 형태로 입력된다.



---
**출력**

입력으로 주어진 단어가 몇 개의 크로아티아 알파벳으로 이루어져 있는지 출력한다.



---

예제 입력 / 출력 예시

입력 : ljes=njak  출력 : 6

입력 : ddz=z=  출력 : 3

입력 : nljj  출력 : 3

입력 : c=c=  출력 : 2


In [14]:

def cro():#메소드 선언 부분
    strs =input() #입력할 문자를 작성하게 만드는 선언문
    cro_voca =['c=','c-','dz=','d-','lj','nj','s=','z='] #크로아티아 알파벳 선언
    for i in range(len(cro_voca)): #배열의 길이만큼 반복문 실행
        strs = strs.replace(cro_voca[i],str(i)) #voca의 문자를 인식하고 그것을 한개의 문자로 만들어줌
    print(len(strs))#크로아티아 알파벳 개수를 출력함
cro()#함수호출   
  


c=c=
2
