# Covariance Matrix(3)
- - -

#### 1. Covariance Matrix - 학습했던 내용!!!

* Calculating the mean of Sample Vectors - HW7 

* Outer product of sample vectors - HW8 

* Covariance Matrix - HW8 

#### 2. 새로운 sample mean vector와 outer product를 구하는 방법으로 Covariance Matrix(HW8의 방법 3 적용) 구하기
* Calculating the mean of a vector & outer product with nan's
* ★Computing the mean together with the covariance★
- - -

#### pyspark import & SparkContext 생성

In [1]:
from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.sql.types import Row, StructField, StructType, StringType, IntegerType

sc = SparkContext(master="local[*]")
print(sc)

# Just like using Spark requires having a SparkContext, using SQL requires an SQLContext
sqlContext = SQLContext(sc)
print(sqlContext)

<SparkContext master=local[*] appName=pyspark-shell>


### 1. Calculating the mean of a vector & outer product with nan's
* We often get vectors $\mathbf{x}$ in which some, but not all, of the entries are `nan`. 
* We want to compute the mean of the elements of $\mathbf{x}$. 
* If we use `np.mean` we will get the result `nan`. 
* A useful alternative is to use `np.nanmean` which removes the `nan` elements and takes the mean of the rest.

#### (1) nan이란 무엇인가
* Not a Number의 약어
* **표현 불가능한 수치형 결과**를 나타내는 값

In [4]:
import numpy as np
a=np.array([1,np.nan,2,np.nan,3,4,5])
print('a=',a)
print('np.mean(a)=',np.mean(a)) # nan이 포함되어 있기 때문에 계산이 되지 않는다.

# nan을 특정한 수치로 처리하여 계산할 것인가? 아니면 빼고 계산할 것인가?
# 사용하고자 하는 방법에 따라 계산된 결과가 다르다!!!!!!!!!
print('np.mean(np.nan_to_num(a))=',np.mean(np.nan_to_num(a))) # =(1+0+2+0+3+4+5)/7
print('np.nanmean(a)=',np.nanmean(a)) # =(1+2+3+4+5)/5

a= [ 1. nan  2. nan  3.  4.  5.]
np.mean(a)= nan
np.mean(np.nan_to_num(a))= 2.142857142857143
np.nanmean(a)= 3.0


#### (2) nan과 관련된 함수들...
* np.nan* 으로 확인
* `np.nan`, `np.isnan`, `np nan_to_num`, `np.nansum`, `np.nanmean` 등등
* 목적에 따라 선택하여 사용할 것.

In [0]:
print("# np.nan을 이용하여 nan을 생성할 수 있다.")
print(np.nan)
print('nan list = ',[np.nan, np.nan, np.nan])

# np.nan을 이용하여 nan을 생성할 수 있다.
nan
nan list =  [nan, nan, nan]


In [0]:
print("# np.isnan을 이용하여 boolean 값을 획득할 수 있다(nan일 경우 True return).")
a = np.array([1,np.nan,2,np.nan,3,4,5])
print("a = ", a)
print("np.isnan(a) = ", np.isnan(a))

# np.isnan을 이용하여 boolean 값을 획득할 수 있다(nan일 경우 True return).
a =  [ 1. nan  2. nan  3.  4.  5.]
np.isnan(a) =  [False  True False  True False False False]


In [0]:
print("# nan_to_num을 이용하여 nan을 특정한 값(0)으로 바꿀 수 있다.")
print("a = ", a)
print("np.nan_to_num(a) = ", np.nan_to_num(a))

# nan_to_num을 이용하여 nan을 특정한 값(0)으로 바꿀 수 있다.
a =  [ 1. nan  2. nan  3.  4.  5.]
np.nan_to_num(a) =  [1. 0. 2. 0. 3. 4. 5.]


In [0]:
print("nan을 특정한 겂으로 처리한 후의 sum = ",sum(np.nan_to_num(a)))
print("nan을 바꾸지 않은 후의 sum = ", sum(a))

nan을 특정한 겂으로 처리한 후의 sum =  15.0
nan을 바꾸지 않은 후의 sum =  nan


**★★ isnan으로부터 생성된 nan의 True/False를 수치형으로 변환**

* `np.isnan(a) = array([False,  True, False,  True, False, False, False])`

* `1-np.isnan(a) = array([1, 0, 1, 0, 1, 1, 1])`  

In [0]:
print("np.isnan(a) = ",np.isnan(a))
print("1-np.isnan(a) = ",1 - np.isnan(a))
print("nan의 개수 파악하기 = ",sum(1-np.isnan(a)))

np.isnan(a) =  [False  True False  True False False False]
1-np.isnan(a) =  [1 0 1 0 1 1 1]
nan의 개수 파악하기 =  5


#### (3) Calculating the mean of a vector with nan's

In [0]:
sum(np.nan_to_num(a))/sum(1-np.isnan(a))

3.0

#### (4) Calculating the outer product of a vector with nan's

In [0]:
S =np.outer(a,a)
N =1-np.isnan(S)

print("outer product with nan\n->", S)
print("\n",N)

outer product with nan
-> [[ 1. nan  2. nan  3.  4.  5.]
 [nan nan nan nan nan nan nan]
 [ 2. nan  4. nan  6.  8. 10.]
 [nan nan nan nan nan nan nan]
 [ 3. nan  6. nan  9. 12. 15.]
 [ 4. nan  8. nan 12. 16. 20.]
 [ 5. nan 10. nan 15. 20. 25.]]

 [[1 0 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 0 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 0 1 0 1 1 1]
 [1 0 1 0 1 1 1]
 [1 0 1 0 1 1 1]]


### Computing the covariance  when there are `nan`s
The covariance is a mean of outer products.

We calculate two matrices:
* $S$ - the sum of the matrices, where `nan`->0
* $N$ - the number of not-`nan` element for each matrix location.

We then calculate the mean as $S/N$ (division is done element-wise)

- - - - - - - - - - - - - -

### 2. Computing the mean together with the covariance

To compute the covariance matrix we need to compute both $\hat{E}(\mathbf{x}^T \mathbf{x})$ and $\hat{E}(\mathbf{x})$. Using a simple trick, we can compute both at the same time.

- - -
(1) Step 1

Here is the trick: lets denote a $d$ dimensional **column vector** by $\mathbf{x} = (x_1,x_2,\ldots,x_d)$ (note that the subscript here is the index of the coordinate, not the index of the example in the training set as used above). 

The augmented vector $\mathbf{x}'$ is defined to be the $d+1$ dimensional vector $\mathbf{x}' = (1,x_1,x_2,\ldots,x_d)$.

- - -
(2) Step 2

The outer product of $\mathbf{x}'$ with itself is equal to 

$$ {\mathbf{x}'}^T {\mathbf{x}'}
= \left[\begin{array}{c|ccc}
    1 &  &{\mathbf{x}'} &\\
    \hline \\
    {\mathbf{x}'}^T & &{\mathbf{x}'}^T {\mathbf{x}'} \\ \\
    \end{array}
    \right]
$$

Where the lower left matrix is the original outer product ${\mathbf{x}'}^T{\mathbf{x}'}$ and the first row and the first column are ${\mathbf{x}'}$ and ${\mathbf{x}'}^T$ respectively.

- - -
(3) Step 3

Now suppose that we do the take the average of the outer product of the augmented vector and convince yourself that:
$$
\hat{E}({\mathbf{x}'}^T{\mathbf{x}'}) = \frac{1}{n} \sum_{i=1}^n {\mathbf{x}'}_i^T{\mathbf{x}'}_i
= \left[\begin{array}{c|ccc}
    1 &  &\hat{E}({\mathbf{x}'}) &\\
    \hline \\
    \hat{E}({\mathbf{x}'}^T) & &\hat{E}({\mathbf{x}'}^T{\mathbf{x}'}) \\ \\
    \end{array}
    \right]
$$

So indeed, we have produced the outer product average together with (two copies of) the average $\hat{E}({\mathbf{x}'}^T)$

**★★★★★여기서 n은 non-nan의 sum★★★★★**

- - -
(4) Step 4

Computing covariance matrix

\begin{align*}
\text{Cov}(\mathbf{x}) &= \hat E({\mathbf{x}'}^T{\mathbf{x}'}) \ - \hat{E}({\mathbf{x}'})^T\hat{E}({\mathbf{x}'})
\end{align*}

In [21]:
# in python
import numpy as np

print("★Step 1★\n")

sample1 = np.array([2,np.nan,3,5], dtype = 'float16')
sample2 = np.array([4,5,np.nan,10], dtype = 'float16')
sample3 = np.array([7,30,9,np.nan], dtype = 'float16')
print("각 sample의 값\n-> ", sample1, sample2, sample3)

# nan이 있는 sample에서 sample mean을 구하기 위한 trick 적용
sample1_trick = np.insert(sample1, 0, 1)
sample2_trick = np.insert(sample2, 0, 1)
sample3_trick = np.insert(sample3, 0, 1)
print("\ntrick이 적용된 각 sample의 값\n-> ", sample1_trick, sample2_trick, sample3_trick)

★Step 1★

각 sample의 값
->  [ 2. nan  3.  5.] [ 4.  5. nan 10.] [ 7. 30.  9. nan]

trick이 적용된 각 sample의 값
->  [ 1.  2. nan  3.  5.] [ 1.  4.  5. nan 10.] [ 1.  7. 30.  9. nan]


In [4]:
# outer product 구하기 
print("★Step 2★\n")

sample1_outer = np.outer(sample1_trick, sample1_trick)
sample2_outer = np.outer(sample2_trick, sample2_trick)
sample3_outer = np.outer(sample3_trick, sample3_trick)

print("sample1_trick의 outer product\n->", sample1_outer)
print("\nsample2_trick의 outer product\n->", sample2_outer)
print("\nsample3_trick의 outer product\n->", sample3_outer)

# outer product의 non-nan 개수 구하기
sample1_outer_nonnan = 1 - np.isnan(sample1_outer)
sample2_outer_nonnan = 1 - np.isnan(sample2_outer)
sample3_outer_nonnan = 1 - np.isnan(sample3_outer)

print("\nsample1_trick outer product의 non-nan\n->", sample1_outer_nonnan)
print("\nsample2_trick outer product의 non-nan\n->", sample2_outer_nonnan)
print("\nsample3_trick outer product의 non-nan\n->", sample3_outer_nonnan)

★Step 2★

sample1_trick의 outer product
-> [[ 1.  2. nan  3.  5.]
 [ 2.  4. nan  6. 10.]
 [nan nan nan nan nan]
 [ 3.  6. nan  9. 15.]
 [ 5. 10. nan 15. 25.]]

sample2_trick의 outer product
-> [[  1.   4.   5.  nan  10.]
 [  4.  16.  20.  nan  40.]
 [  5.  20.  25.  nan  50.]
 [ nan  nan  nan  nan  nan]
 [ 10.  40.  50.  nan 100.]]

sample3_trick의 outer product
-> [[  1.   7.  30.   9.  nan]
 [  7.  49. 210.  63.  nan]
 [ 30. 210. 900. 270.  nan]
 [  9.  63. 270.  81.  nan]
 [ nan  nan  nan  nan  nan]]

sample1_trick outer product의 non-nan
-> [[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]

sample2_trick outer product의 non-nan
-> [[1 1 1 0 1]
 [1 1 1 0 1]
 [1 1 1 0 1]
 [0 0 0 0 0]
 [1 1 1 0 1]]

sample3_trick outer product의 non-nan
-> [[1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 0]
 [0 0 0 0 0]]


In [5]:
# outerproduct의 sum
print("★Step 3★\n")

sample_outer_sum = np.nansum(np.dstack([sample1_outer, sample2_outer]), axis=2)
sample_outer_sum = np.nansum(np.dstack([sample_outer_sum, sample3_outer]), axis=2)
print("sample outer product sum\n->", sample_outer_sum)

# non-name의 sum
sample_nonnan_sum = sample1_outer_nonnan + sample2_outer_nonnan + sample3_outer_nonnan
print("\nsample non-nan sum\n->", sample_nonnan_sum)

print("\nsample mean vector\n->", 
      sample_outer_sum[0, 1:] / np.float16(sample_nonnan_sum[0, 1:]))
print("\nouter product의 sum\n->",\
      sample_outer_sum[1:, 1:] / np.float16(sample_nonnan_sum[1:, 1:]))

★Step 3★

sample outer product sum
-> [[  3.  13.  35.  12.  15.]
 [ 13.  69. 230.  69.  50.]
 [ 35. 230. 925. 270.  50.]
 [ 12.  69. 270.  90.  15.]
 [ 15.  50.  50.  15. 125.]]

sample non-nan sum
-> [[3 3 2 2 2]
 [3 3 2 2 2]
 [2 2 2 1 1]
 [2 2 1 2 1]
 [2 2 1 1 2]]

sample mean vector
-> [ 4.332 17.5    6.     7.5  ]

outer product의 sum
-> [[ 23.  115.   34.5  25. ]
 [115.  462.5 270.   50. ]
 [ 34.5 270.   45.   15. ]
 [ 25.   50.   15.   62.5]]


In [6]:
# Computing covariance matrix(HW8의 3번째 방법 이용)
print("★Step 4★\n")

sample_mean_vector = sample_outer_sum[0, 1:] / np.float16(sample_nonnan_sum[0, 1:])
sample_outer_sum = sample_outer_sum[1:, 1:] / np.float16(sample_nonnan_sum[1:, 1:])

cov = sample_outer_sum - np.outer(sample_mean_vector, sample_mean_vector)
print("Covariance Matrix\n->", cov)

★Step 4★

Covariance Matrix
-> [[  4.234  39.2     8.5    -7.5  ]
 [ 39.2   156.2   165.    -81.25 ]
 [  8.5   165.      9.    -30.   ]
 [ -7.5   -81.25  -30.      6.25 ]]


### Excercise 1 - 
#### 위의 Example에서 Python으로 적용한 부분을 Spark로 적용해보자!! (40 point)

- - -

다음 데이터에 대하여 다음 과제를 수행하세요.

```
sample1 = np.array([2,np.nan,3,5])
sample2 = np.array([4,5,np.nan,10])
sample3 = np.array([7,30,9,np.nan])
```

위에서 진행된 Step 1 ~ Step 4(Python)를 Spark로 구현하세요!!

**task**

* 1 : Step 1 (10 point)

<br>

* 2 : Step 2 (10 point)

<br>

* 3 : Step 3 (10 point)

<br>

* 4 : Step 4 (10 point)

**task**

* 1 : Here is the trick: lets denote a $d$ dimensional **column vector** by $\mathbf{x} = (x_1,x_2,\ldots,x_d)$ (note that the subscript here is the index of the coordinate, not the index of the example in the training set as used above). 

The augmented vector $\mathbf{x}'$ is defined to be the $d+1$ dimensional vector $\mathbf{x}' = (1,x_1,x_2,\ldots,x_d)$. (10 point)
- - -
```
# task 1-1 output
[array([ 1.,  2., nan,  3.,  5.], dtype=float16),
 array([ 1.,  4.,  5., nan, 10.], dtype=float16),
 array([ 1.,  7., 30.,  9., nan], dtype=float16)]
 ```

In [13]:
# task 1-1 답안 작성

import numpy as np#numpy함수 활용
task1_1=sc.parallelize([sample1,sample2,sample3])#task1_1에 sample1,2,3의 리스트를 rdd형태로 만들어줌
a=task1_1.map(lambda x:np.insert(x,0,1))#a에 task1_1 rdd에 0번째 원소에 1을 넣고 np array 형태로 만들어서 저장
# output
print("# task 1-1 output")#task1_1을 출력
a.collect()                        

NameError: name 'sample1' is not defined

**task**

* 2 : 

The outer product of $\mathbf{x}'$ with itself is equal to 

$$ {\mathbf{x}'}^T {\mathbf{x}'}
= \left[\begin{array}{c|ccc}
    1 &  &{\mathbf{x}} &\\
    \hline \\
    {\mathbf{x}}^T & &{\mathbf{x}}^T {\mathbf{x}} \\ \\
    \end{array}
    \right]
$$

Where the lower left matrix is the original outer product ${\mathbf{x}'}^T{\mathbf{x}'}$ and the first row and the first column are ${\mathbf{x}'}$ and ${\mathbf{x}'}^T$ respectively.

- - -

**★ sample의 outer prodcut와 outer product의 non-nan을 구할 것.!!**

```
# task 1-2
sample outer product
-> [array([[ 1.,  2., nan,  3.,  5.],
       [ 2.,  4., nan,  6., 10.],
       [nan, nan, nan, nan, nan],
       [ 3.,  6., nan,  9., 15.],
       [ 5., 10., nan, 15., 25.]], dtype=float16), array([[  1.,   4.,   5.,  nan,  10.],
       [  4.,  16.,  20.,  nan,  40.],
       [  5.,  20.,  25.,  nan,  50.],
       [ nan,  nan,  nan,  nan,  nan],
       [ 10.,  40.,  50.,  nan, 100.]], dtype=float16), array([[  1.,   7.,  30.,   9.,  nan],
       [  7.,  49., 210.,  63.,  nan],
       [ 30., 210., 900., 270.,  nan],
       [  9.,  63., 270.,  81.,  nan],
       [ nan,  nan,  nan,  nan,  nan]], dtype=float16)]

sample outer product non-nan
-> [array([[1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1]]), array([[1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1]]), array([[1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])]
```

In [8]:
# task 1-2 답안 작성
task1_2=a.map(lambda x:np.outer(x,x))#task1_2에 a의 값을 map을 통해 외적시켜서 저장함
outer_nonnan=task1_2.map(lambda x:1-np.isnan(x))#outer_nonnan에 task1_2의 맵과 isnan을 하여 nonnan갯수를 저장해줌
# output
print("sample outer product\n->", task1_2.collect())#task1_2를 출력
print("\nsample outer product non-nan\n->", outer_nonnan.collect())#outer_nonnan을 출력



sample outer product
-> [array([[ 1.,  2., nan,  3.,  5.],
       [ 2.,  4., nan,  6., 10.],
       [nan, nan, nan, nan, nan],
       [ 3.,  6., nan,  9., 15.],
       [ 5., 10., nan, 15., 25.]], dtype=float16), array([[  1.,   4.,   5.,  nan,  10.],
       [  4.,  16.,  20.,  nan,  40.],
       [  5.,  20.,  25.,  nan,  50.],
       [ nan,  nan,  nan,  nan,  nan],
       [ 10.,  40.,  50.,  nan, 100.]], dtype=float16), array([[  1.,   7.,  30.,   9.,  nan],
       [  7.,  49., 210.,  63.,  nan],
       [ 30., 210., 900., 270.,  nan],
       [  9.,  63., 270.,  81.,  nan],
       [ nan,  nan,  nan,  nan,  nan]], dtype=float16)]

sample outer product non-nan
-> [array([[1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1],
       [1, 1, 0, 1, 1]]), array([[1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1]]), array([[1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 

**task**

* 3 : 

Now suppose that we do the take the average of the outer product of the augmented vector and convince yourself that:
$$
\hat{E}({\mathbf{x}'}^T{\mathbf{x}'}) = \frac{1}{n} \sum_{i=1}^n {\mathbf{x}'}_i^T{\mathbf{x}'}_i
= \left[\begin{array}{c|ccc}
    1 &  &\hat{E}({\mathbf{x}}) &\\
    \hline \\
    \hat{E}({\mathbf{x}}^T) & &\hat{E}({\mathbf{x}}^T{\mathbf{x}}) \\ \\
    \end{array}
    \right]
$$

So indeed, we have produced the outer product average together with (two copies of) the average $\hat{E}({\mathbf{x}'}^T)$

- - -

**★★★★★여기서 n은 non-nan의 sum!!★★★★★**

```
# task 1-3 
outer product sum(n이 나누어지지 않은)
-> [[  3.  13.  35.  12.  15.]
 [ 13.  69. 230.  69.  50.]
 [ 35. 230. 925. 270.  50.]
 [ 12.  69. 270.  90.  15.]
 [ 15.  50.  50.  15. 125.]]

outer product non-nan sum
-> [[3 3 2 2 2]
 [3 3 2 2 2]
 [2 2 2 1 1]
 [2 2 1 2 1]
 [2 2 1 1 2]]

outer product sum(n이 나누어진)
-> [[ 23.  115.   34.5  25. ]
 [115.  462.5 270.   50. ]
 [ 34.5 270.   45.   15. ]
 [ 25.   50.   15.   62.5]]

sample mean vector
-> [ 4.332 17.5    6.     7.5  ]
```

In [9]:
# task 1-3 답안 작성

task1_3_outer_sum=task1_2.reduce(lambda x,y:(np.nansum(np.dstack([x, y]), axis=2)))#task1_3_outer_sum에 task1_2값을 리듀스하여 전부 더해주고 리스트 형태로 반환
task1_3_nonnan_sum=outer_nonnan.reduce(lambda x,y:(np.nansum(np.dstack([x,y]),axis=2)))#task1_3_nonnan_sum에 outer_nonnan을 리듀스하여 전부 더해주고 리스트 형태로 반환
sample_outer_product=(task1_3_outer_sum[1:, 1:] / np.float16(task1_3_nonnan_sum[1:, 1:]))#sample_outer_product의 순수한 외적만을 저장하기 위해 전부 더한 outersum의 1행1열을 논난 1행 1열로 나눔
sample_mean_vector= (task1_3_outer_sum[0, 1:] / np.float16(task1_3_nonnan_sum[0, 1:]))#sample_mean_vector는 0행1열 이므로 task1_3outersum에서 0행1열과 논난 썸 0행1열을 나눠서 넣음

# output
print("outer product sum(n이 나누어지지 않은)\n->", task1_3_outer_sum)#task1_3outer_sum출력
print("\nouter product non-nan sum\n->", task1_3_nonnan_sum)#task1_3nonnn_sum을 출력
print("\nouter product sum(n이 나누어진)\n->", sample_outer_product)#sample_outer_product를 출력
print("\nsample mean vector\n->", sample_mean_vector)#sample_mean_vector 출력


outer product sum(n이 나누어지지 않은)
-> [[  3.  13.  35.  12.  15.]
 [ 13.  69. 230.  69.  50.]
 [ 35. 230. 925. 270.  50.]
 [ 12.  69. 270.  90.  15.]
 [ 15.  50.  50.  15. 125.]]

outer product non-nan sum
-> [[3 3 2 2 2]
 [3 3 2 2 2]
 [2 2 2 1 1]
 [2 2 1 2 1]
 [2 2 1 1 2]]

outer product sum(n이 나누어진)
-> [[ 23.  115.   34.5  25. ]
 [115.  462.5 270.   50. ]
 [ 34.5 270.   45.   15. ]
 [ 25.   50.   15.   62.5]]

sample mean vector
-> [ 4.332 17.5    6.     7.5  ]


**task**

* 4 :

Computing covariance matrix

\begin{align*}
\text{Cov}(\mathbf{x}) &= \hat E({\mathbf{x}}^T{\mathbf{x}}) \ - \hat{E}({\mathbf{x}})^T\hat{E}({\mathbf{x}})
\end{align*}

- - -


```
# task 1-4
covariance matrix
-> [[  4.234  39.2     8.5    -7.5  ]
 [ 39.2   156.2   165.    -81.25 ]
 [  8.5   165.      9.    -30.   ]
 [ -7.5   -81.25  -30.      6.25 ]]
```

In [10]:
# task 1-4 답안 작성
cov=sample_outer_product - np.outer(sample_mean_vector, sample_mean_vector)#공분산 식에 따라 구해준 mean vector외적값을 총 외적 합에서 빼주고 저장
# output
print("covariance matrix\n->", cov)#공분산값 출력

covariance matrix
-> [[  4.234  39.2     8.5    -7.5  ]
 [ 39.2   156.2   165.    -81.25 ]
 [  8.5   165.      9.    -30.   ]
 [ -7.5   -81.25  -30.      6.25 ]]


### Excercise 2 - 
####  (60 point)

- - -

다음 데이터에 대하여 다음 과제를 수행하세요.

- regular_float32.zip : KBO에서 활약한 타자들의 역대 정규시즌 성적을 포함하여 타자의 고유 아이디, 타자의 이름, 팀 이름, 기록, 년도 등을 포함한 parquet 파일 입니다.

```
# regular_float32 예시
<regular_float32.show(5)>
+---------+------+----+--------------------+----+
|batter_id|  name|team|              values|year|
+---------+------+----+--------------------+----+
|      297|진갑용|삼성|[17 D9 8E 3E 00 0...|2008|
|      297|진갑용|삼성|[68 91 6D 3E 00 0...|2009|
|      297|진갑용|삼성|[F0 A7 86 3E 00 0...|2010|
|      297|진갑용|삼성|[A8 C6 8B 3E 00 0...|2011|
|      297|진갑용|삼성|[1B 2F 9D 3E 00 0...|2012|
+---------+------+----+--------------------+----+
only showing top 5 rows

<schema>
root
 |-- batter_id: long (nullable = true)
 |-- name: string (nullable = true)
 |-- team: string (nullable = true)
 |-- values: binary (nullable = true)
 |-- year: long (nullable = true)

<row의 수(sample의 수)> :2454
```

- - -

##### regular_float32의 values에 대한 정보
    A. values는 byte array로 각각의 값은 float32로 이루어져 있습니다.
    B. values에 포함된 값은 아래와 같습니다(index 순서와 동일).
       [0]타율 [1]출전게임수 [2]타수(타석-볼넷-사구-희생번트-희생플라이)
       [3]득점 [4]안타(1루타+2루타+3루타+홈런) [5]2루타 [6]3루타
       [7]홈런 [8]루타 수 [9]타점 [10]도루 성공 [11]도루 실패 [12]볼넷
       [13]사구(몸에 맞는 볼) [14]삼진아웃 [15]병살타 [16]장타율 [17]출루율
       [18]에러
    C. values의 포함된 값은 nan이 존재할 수 있습니다.
    D. values를 ndarray로 변환시에는 dtype="float32"를 사용하세요.
    
    
- - -
##### Excercise 2에서 포함되어야 할 사항
    A. 모든 작업은 RDD로 수행합니다.
    B. Excercise 1에서 진행했던 모든 단계를 함수화 합니다.
        (1) 함수의 이름, 기능은 자유롭게 설정합니다(1개 또는 여러개를 사용해도 됩니다)
        (2) 단, 작성된 함수를 종합하여 실행하는 함수를 만들어야 합니다(ex. calcCov)
    C. check_symmetric :  True, Exercise2 shape :  (19, 19) 가 결과로 출력되는지 확인하세요.
    D. covariance matrix를 구한 후, regular_cov.txt 파일로 저장하여 과제란에 같이 제출합니다.

- - -
```
# Exercise 2 output
check_symmetric :  True

Exercise2 shape :  (19, 19)

Exercise2 result
-> [[9.68648770e-03 2.31904584e+00 8.71907655e+00 1.45815861e+00
  2.81985552e+00 4.96244952e-01 4.60792588e-02 3.05693491e-01
  4.32533845e+00 1.44053534e+00 2.43099885e-01 9.82517298e-02
  9.88237934e-01 1.42195695e-01 1.39666974e+00 1.98392683e-01
  1.39535328e-02 9.58807760e-03 1.26492938e-01],
                ...(중간 생략)...
 [1.26492938e-01 1.19444102e+02 4.45646963e+02 6.70115876e+01
  1.28225598e+02 2.35202158e+01 2.19940931e+00 1.39919460e+01
  1.98120470e+02 6.50261108e+01 1.26920823e+01 5.25860146e+00
  4.43497757e+01 8.11945502e+00 7.72257562e+01 1.05942064e+01
  2.23718629e-01 1.35275737e-01 2.10159326e+01]]
 ```
(regular_cov.txt 예시)

<p><img alt="" src="https://drive.google.com/uc?id=1bIZAMXlyxw_WtZtiYaDBmlCH6MkZUDil" style="height:324px; width:900px" /></p>

In [ ]:
import urllib.request
from os.path import exists

!mkdir regular.parquet


f = urllib.request\
.urlretrieve ("https://docs.google.com/uc?export=download&id=1GUP0n9aybONtLkGre8GnBMBpMgR777Wy",
              "./regular_float32.zip")


!unzip regular_float32.zip -d regular.parquet/
!rm -rf regular_float32.zip


"""
f = urllib.request\
.urlretrieve ("https://docs.google.com/uc?export=download&id=1fbTRIL2HGRYss0FnrwcM1lgZ0nm0pjVE",
              "./regular_float16.zip")
"""

mkdir: cannot create directory ‘regular.parquet’: File exists
Archive:  regular_float32.zip
replace regular.parquet/._SUCCESS.crc? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [2]:
# data 읽기
data = sqlContext.read.parquet("./regular.parquet/")

data.show(5)
data.printSchema()
data.count()

+---------+------+----+--------------------+----+
|batter_id|  name|team|              values|year|
+---------+------+----+--------------------+----+
|      297|진갑용|삼성|[17 D9 8E 3E 00 0...|2008|
|      297|진갑용|삼성|[68 91 6D 3E 00 0...|2009|
|      297|진갑용|삼성|[F0 A7 86 3E 00 0...|2010|
|      297|진갑용|삼성|[A8 C6 8B 3E 00 0...|2011|
|      297|진갑용|삼성|[1B 2F 9D 3E 00 0...|2012|
+---------+------+----+--------------------+----+
only showing top 5 rows

root
 |-- batter_id: long (nullable = true)
 |-- name: string (nullable = true)
 |-- team: string (nullable = true)
 |-- values: binary (nullable = true)
 |-- year: long (nullable = true)



2454

In [5]:
a=data.rdd.map(lambda x:np.frombuffer(x.values,dtype="float32")).map(lambda x:(np.insert(x,0,1)))#array에 1씩 추가
b=a.map(lambda x:(np.outer(x,x)))#외적 
c=b.map(lambda x:1-np.isnan(x)).map(lambda x:np.outer(x,x))#non-nan
d=c.map(lambda x:np.nansum(np.dstack([x, x]), axis=2))#non합
e=b.map(lambda x:np.nansum(np.dstack([x, x]), axis=2))#외적 합
d+e
#def aa(SampleA,SampleB):
   # a=SampleA+SampleB.map(lambda x:((SampleA,SampleB)))
   # return a
    
    
#aa(e,d)
    

#print("\nsample mean vector\n->", 
     # sample_outer_sum[0, 1:] / np.float16(sample_nonnan_sum[0, 1:]))
#print("\nouter product의 sum\n->",\
     # sample_outer_sum[1:, 1:] / np.float16(sample_nonnan_sum[1:, 1:]))






UnionRDD[18] at union at NativeMethodAccessorImpl.java:0

In [11]:
# Exercise 2 답안 작성
# 작성 예시
def Ndarray2Trick(row):
    row=row.rdd.map(lambda x:np.frombuffer(x.values,dtype="float32")).map(lambda x:(np.insert(x,0,1)))
    #row를 rdd로 바꾸고 map을 통해 값들을 float32형태로 바꿔주고 모든 원소의 값 0번쨰에 1을 넣어주고 np.array형태로 만들어줌
    return row #row를 반환
    # row를 input으로 받아서 각 array에 1 을 추가하여 np.array return하는 함수 
    

def outerWithNan(arr):
    O=arr.map(lambda x:np.outer(x,x))#O값에 map을 통하여 외적값을 넣어 저장시켜줌
    N=O.map(lambda x:1-np.isnan(x))#N값에 map을 통하여 isnan을 하고 nonnan값만을 구해주고 저장
    return [O,N]#리스트 형태로 O,N을 반환시켜줌
    # O = outer product, 
    # N = non-nan of outer prodcut
    
    # return [O, N]

def sumWithNan(outer):
    # SampleA,B ----> [0] = outer product, [1] = non-nan of outer product
    sum_outer = outer[0].reduce(lambda x,y:np.nansum(np.dstack([x, y]), axis=2))#sum_outer에 outer[0]즉 outerproudct를 뽑아내고 그것들끼리 reduce하여 값들을 전부 더함
    sum_nonnan =outer[1].reduce(lambda x,y:np.nansum(np.dstack([x, y]), axis=2))#sum_nonnan에 outer[1]즉 non-nan of outer product를 뽑아내고 그것들끼리 reduce하여 값들을 전부 더함
    return [sum_outer,sum_nonnan]#두 개 값들을 리스트 형태로 반환
    

def calc_func(sum_list):
    # E -> sum outer의 mean  추출
    E=sum_list[0][1:,1:]/sum_list[1][1:,1:] #E는 받은 sum_list에 [0](outerproduct의 합)/sum_list(non-nan의 합)을 나눠줌 1행 1열이여야만 순수한 sum outer의 mean이 나옴
   
    # NE -> sum nonnan의 mean에 사용할 nonnan 수 추출
    NE=sum_list[0][1:,0]/sum_list[1][1:,0] #NE는 sumlist[0](outerproduct의 합 )/sum_list(non-nan의 합)을 나눠줌 1행 0열만이 그 순수한 값이기 때문에 그것만 뽑아내줌
    # Mean_vector 연산
    Mean_vector=sum_list[0][0,1:]/sum_list[1][0,1:]#Mean_vector는 sum_list[0](outerproduct의 합 )/sum_list(non-nan의 합) 0행 1열만의 그 순수한 값이기 때문에 그것만 뽑아내줌
    # Outer_vector = 
    Outer_vector=E-(np.outer(NE,Mean_vector))#공분산 값을 outer_vector에 저장하는데 E는 총 외적값을 non-nan으로 나눠서 나온 값-(sum nonnan의 평균,Sample_vector)외적
    
    return  Outer_vector#공분산 값을 반환
    
def calcCov(DataFrame):
    # 위 함수를 활용하여 DataFrame을 calc_func 입력 변환 사전작업
    # Result_cacl = calc_func(sumResult)
    df_RDD = Ndarray2Trick(DataFrame)#함수에 dataFrame을 넣어줌
    df_outer = outerWithNan(df_RDD)#저장한 df_RDD에 outerWithNan을 사용
    df_sum = sumWithNan(df_outer)#저장한 df_outer에 sunWithNan함수를 사용
    
    
    Result_cacl = calc_func(df_sum)#calc_func에 df_sum을 넣고 Reslt_cacl에 저장
    #  Cov =
    Cov=Result_cacl #그 값을 Cov에 저장
    
    return Cov#cov값을 반환
    # return Cov

In [12]:
# Exercise 2 output
def check_symmetric(a, rtol=1e-05, atol=1e-08):
    return np.allclose(a, a.T, rtol=rtol, atol=atol)

Exercise2_Cov = calcCov(data)#Exercis2_Cov에 calcCov(data)를 넣어서 저장
print("check_symmetric : ", check_symmetric(Exercise2_Cov))#출력
print("\nExercise2 shape : ", Exercise2_Cov.shape)#형태 출력
print("\nExercise2 result\n->", Exercise2_Cov)# Exercis2_cov출력

# textFile로 저장 후 주피터 노트북과 같이 제출
np.savetxt("regular_cov.txt", Exercise2_Cov, delimiter="\t")

check_symmetric :  True

Exercise2 shape :  (19, 19)

Exercise2 result
-> [[9.68649964e-03 2.31904444e+00 8.71907518e+00 1.45815936e+00
  2.81986175e+00 4.96245200e-01 4.60792829e-02 3.05693730e-01
  4.32534540e+00 1.44053684e+00 2.43100420e-01 9.82518388e-02
  9.88238461e-01 1.42195479e-01 1.39667151e+00 1.98392899e-01
  1.39534918e-02 9.58810981e-03 1.26493030e-01]
 [2.31904444e+00 2.03262815e+03 7.11935584e+03 1.11504810e+03
  2.10245742e+03 3.70960571e+02 3.62472065e+01 2.27622310e+02
  3.22877893e+03 1.08292775e+03 2.00688691e+02 8.28696508e+01
  7.78887464e+02 1.19269553e+02 1.23565084e+03 1.60837245e+02
  4.03568690e+00 2.64932240e+00 1.19444102e+02]
 [8.71907518e+00 7.11935584e+03 2.87308044e+04 4.61456465e+03
  8.72583045e+03 1.54633717e+03 1.48994509e+02 9.85854260e+02
  1.35277223e+04 4.53493811e+03 8.40269582e+02 3.34447804e+02
  3.20356317e+03 4.66056526e+02 4.78575510e+03 6.45422076e+02
  1.56792351e+01 9.74128234e+00 4.45646963e+02]
 [1.45815936e+00 1.11504810e+03 4.6145

### ㅎㅎ~
![hi](https://contents.vryjam.com/g1TwHtUsHsPFaeQ.gif)